### ISSUE TITLE
Version in NPM is different then here

### ISSUE THREAD

**Issue by pashidlos** [visual-knight/libraries#8]
- https://www.npmjs.com/package/@visual-knight/core (v2.0.0-alpha.0)
- https://github.com/visual-knight/libraries/releases (v1.0.1)

was it deployed from `feat/community-version` branch?
shall we merge this?
https://github.com/visual-knight/libraries/compare/feat/community-version

**Comment by MitkoTschimev** [comment]
Yes, it was deployed from the community branch with the alpha version. Since we shut down the commercial usage we can merge it

**Comment by pashidlos** [comment]
PR created https://github.com/visual-knight/libraries/pull/10

**Comment by MitkoTschimev** [comment]
merged
